### ISSUE TITLE
The tunnel returns an error

### ISSUE THREAD

**Issue by bogdanr** [gbip/sentry_tunnel#3]
I configured the tunnel with the docker image but it returns an error like this one:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RelativeUrlWithoutBase', src/envelope.rs:75:36
stack backtrace:
   0:     0x7f5316af1a50 - std::backtrace_rs::backtrace::libunwind::trace::hb16dbf761681cfc0
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f5316af1a50 - std::backtrace_rs::backtrace::trace_unsynchronized::h53bc5f57122de54d
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f5316af1a50 - std::sys_common::backtrace::_print_fmt::h7e86959aa36cde43
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f5316af1a50 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf42958820747a8ac
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f5316b2f5ec - core::fmt::write::h6f5ededa5074697e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
   5:     0x7f5316aec4c5 - std::io::Write::write_fmt::hdb84dc6c28fda870
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
   6:     0x7f5316af3a2b - std::sys_common::backtrace::_print::hbb646398d13d0dcb
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f5316af3a2b - std::sys_common::backtrace::print::ha3796c9cf0c5a732
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f5316af3a2b - std::panicking::default_hook::{{closure}}::hb85a09d7e9a16432
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:     0x7f5316af3501 - std::panicking::default_hook::hdc924e74cb190bbb
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:     0x7f5316af40f4 - std::panicking::rust_panic_with_hook::hd63b080e78590a80
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:622:17
  11:     0x7f5316af3bd7 - std::panicking::begin_panic_handler::{{closure}}::h27bfba1f7e931f90
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
  12:     0x7f5316af1eec - std::sys_common::backtrace::__rust_end_short_backtrace::h2cc025f6c95b1f82
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x7f5316af3b39 - rust_begin_unwind
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
  14:     0x7f53166dcfc1 - core::panicking::panic_fmt::h9f5a85773697c5f5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
  15:     0x7f53166dd0b3 - core::result::unwrap_failed::h43465fb8e3273283
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
  16:     0x7f5316766436 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::he5a303e7c20755b8
  17:     0x7f531676a8ca - sentry_tunnel::envelope::SentryEnvelope::dsn_host_is_valid::h30a61ee7ef4bf7a3
  18:     0x7f53167614cf - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h45378b13883fce05
  19:     0x7f53169a2299 - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::h44031fba5a98df6f
  20:     0x7f53169a8723 - <futures_util::future::try_future::try_flatten_err::TryFlattenErr<Fut,<Fut as futures_core::future::TryFuture>::Error> as core::future::future::Future>::poll::hffbccbab3c0ac311
  21:     0x7f53169a2087 - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::h14a2da13cf059196
  22:     0x7f53169b544e - <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll::hc75c02f2ccdc0150
  23:     0x7f53169a6899 - <futures_util::future::try_future::AndThen<Fut1,Fut2,F> as core::future::future::Future>::poll::h447c699d0fe8a828
  24:     0x7f531671fa55 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9fb6797044475bd9
  25:     0x7f531671f398 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h6f29778b3c2e7dbb
  26:     0x7f531671a7ac - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner::h2b6debe1116855b1
  27:     0x7f531674cb08 - <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll::hdcf8a662511ecb96
  28:     0x7f5316705b8b - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h61d1508f30d73881
  29:     0x7f531671fc4c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb8a6706da5256738
  30:     0x7f531675508e - tokio::runtime::task::core::CoreStage<T>::poll::hb55bce37b34d2b50
  31:     0x7f531670feb7 - tokio::runtime::task::harness::poll_future::he66fdad49a51c82e
  32:     0x7f5316710ddf - tokio::runtime::task::harness::Harness<T,S>::poll::h3481a8149d288967
  33:     0x7f5316abeb06 - tokio::runtime::thread_pool::worker::Context::run_task::h484d166afc49137b
  34:     0x7f5316abd927 - tokio::runtime::thread_pool::worker::Context::run::he56ca1e64e14a46b
  35:     0x7f5316aaa803 - tokio::macros::scoped_tls::ScopedKey<T>::set::h4f4d6d229172db0a
  36:     0x7f5316abd1c1 - tokio::runtime::thread_pool::worker::run::h10dbecfad0c64130
  37:     0x7f5316ac39f1 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hcca2e7104e44bce9
  38:     0x7f5316aa65f8 - tokio::runtime::task::harness::Harness<T,S>::poll::h39ba1fac2c9f2fc6
  39:     0x7f5316ab39d1 - tokio::runtime::blocking::pool::Inner::run::hca3bbe70b8fdad36
  40:     0x7f5316aa72cb - std::sys_common::backtrace::__rust_begin_short_backtrace::h5a2acef6ae0efedd
  41:     0x7f5316ac5518 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h00a79e75441986e7
  42:     0x7f5316af74b7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4b43062ddf86e957
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
  43:     0x7f5316af74b7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h140d9feeaae0eb97
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
  44:     0x7f5316af74b7 - std::sys::unix::thread::Thread::new::thread_start::hf02895d7c8c67d27
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys/unix/thread.rs:74:17
```
Any idea why?

**Comment by gbip** [comment]
I'll take a look.

**Comment by gbip** [comment]
Ok, this seems to be an error in your remote_host configuration. I'll improve the error message.
